### ISSUE TITLE
Не создается проект.

### ISSUE THREAD

**Issue by ShockWave2048** [code-orchestra/colt-build#13]
Ставлю, запускаю, "New ActionScript project", выбираю папку, ничего не происходит. Файла проекта нет, панели управления/терминала нет.
Готовые (примеры) проекты открываются, панель есть,

**Comment by illuzor** [comment]
Наблюдаю то же самое

**Comment by SlavaRa** [comment]
Ребят, а sdk, которую предлагается скачать в самом начале вы скачали?

**Comment by ShockWave2048** [comment]
да, 4.6

**Comment by SlavaRa** [comment]
Я имею ввиду, когда при первом запуске предлагается скачать flex sdk, он качает "свою" сдк и кладет ее в папку программы user/AppData/Local/Colt/app/flex_sdk 
там кстати не может быть flex sdk 4.6, там должна быть flex sdk 4.14.1 FP 18 AIR 18

**Comment by SlavaRa** [comment]
Нашел ошибку, проявляется только в установленной версии, вечером будет фикс, ребят спасибо за помощь :)

**Comment by ShockWave2048** [comment]
а ну да, 4,14
в принципе он только с ней стартует сборку
(хотя не компилит, в корневом ас классе ругается на класс Sprite - который flash.display.Sprite)

**Comment by SlavaRa** [comment]
https://github.com/code-orchestra/colt-build/releases/tag/1.3.1
